#!/usr/bin/env bash
# A Bash script that loops from 1 to 10 and:
# display bad luck for the 4th loop iteration
# display good luck for the 8th loop iteration
# display Best School for the other iterations

printBestSchool=1
while [ $printBestSchool -lt 11 ]
do
	if [ "$printBestSchool" == "4" ]
	then
		echo "bad luck"
	elif [ "$printBestSchool" == "8" ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	printBestSchool=$((printBestSchool+1))
done
